server:
  port: 8081
spring:
  application:
    name: poker-game-auth
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC
    property-naming-strategy: SNAKE_CASE
  cloud:
    nacos:
      discovery:
        server-addr: http://127.0.0.1:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/poker_game_auth_db?serverTimezone=UTC&useUnicode=true@characterEncoding=utf-8
    username: root
    password: 123456
    # 初始连接数 最小连接数 最大连接数
    initial-size: 10
    min-idle: 10
    max-active: 100
    # 配置获取连接等待超时的时间 60s
    max-wait: 60000
    validation-query: SELECT 1
    # 申请连接时进行测试连接
    test-while-idle: true
    # 空闲连接检测时间
    time-between-eviction-runs-millis: 60000
    # 是否开启PSCache，对支持游标的数据库性能提示巨大，oracle建议开启，mysql下建议关闭
    pool-prepared-statements: false
  jpa:
    hibernate:
      ddl-auto: update

# 日志配置
logging:
  file:
    name: poker-game-auth.log
    path: G:/JavaProject/git/poker-game/logs
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 5