server:
  port: 8080
spring:
  application:
    name: poker-game-gateway
  cloud:
    nacos:
      discovery:
        server-addr: http://127.0.0.1:8848
    gateway:
      routes:
        - id: poker-game-auth
          uri: lb://poker-game-auth
          predicates:
            - Path=/poker-game-auth/**