spring:
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/poker-game-db?serverTimezone=UTC&useUnicode=true@characterEncoding=utf-8
      username: root
      password: 123456
      # 初始连接数 最小连接数 最大连接数
      initial-size: 10
      min-idle: 10
      max-active: 100
      # 配置获取连接等待超时的时间 60s
      max-wait: 60000
      validation-query: SELECT 1
      # 申请连接时进行测试连接
      test-while-idle: true
      # 空闲连接检测时间
      time-between-eviction-runs-millis: 60000
      # 是否开启PSCache，对支持游标的数据库性能提示巨大，oracle建议开启，mysql下建议关闭
      pool-prepared-statements: false
  flyway:
    enabled: true
    encoding: UTF-8
    # flyway执行记录表名
    table: flyway_schema_history
    # 当数据库存在但表不存在时，自动执行基准迁移，新建flyway_schema_history表
    baseline-version: 1
    baseline-on-migrate: true
    # 执行时验证脚本
    validate-on-migrate: true
    # sql脚本位置
    locations: classpath:db/migration
    # SQL迁移脚本文件名，前缀v，后缀.sql
    sql-migration-prefix: v
    sql-migration-suffixes: .sql
    # 禁用clean操作
    clean-disabled: true

